# Generated by Django 3.2.8 on 2021-11-16 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_comment_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image_pro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('image_pro', models.ImageField(blank=True, null=True, upload_to='image_pro/')),
                ('product_img', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.product')),
            ],
        ),
    ]
