# Generated by Django 3.2.8 on 2021-11-29 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='code',
            field=models.CharField(default=1, max_length=8),
            preserve_default=False,
        ),
    ]
